# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Digital_Sys_Design/Basys-3-Master.xdc

# Block Designs: bd/ball64x448/ball64x448.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ball64x448 || ORIG_REF_NAME==ball64x448} -quiet] -quiet

# IP: bd/ball64x448/ip/ball64x448_blk_mem_gen_0_0/ball64x448_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ball64x448_blk_mem_gen_0_0 || ORIG_REF_NAME==ball64x448_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/cat64x128/cat64x128.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cat64x128 || ORIG_REF_NAME==cat64x128} -quiet] -quiet

# IP: bd/cat64x128/ip/cat64x128_blk_mem_gen_0_0/cat64x128_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cat64x128_blk_mem_gen_0_0 || ORIG_REF_NAME==cat64x128_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Digital_Sys_Design/vga_sprites/vga_sprites.gen/sources_1/bd/ball64x448/ball64x448_ooc.xdc

# XDC: c:/Digital_Sys_Design/vga_sprites/vga_sprites.gen/sources_1/bd/cat64x128/cat64x128_ooc.xdc
