# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Digital_Sys_Design/vga_sprites/vga_sprites.srcs/sources_1/bd/cat64x128/ip/cat64x128_blk_mem_gen_0_0/cat64x128_blk_mem_gen_0_0.xci
# IP: The module: 'cat64x128_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Digital_Sys_Design/vga_sprites/vga_sprites.gen/sources_1/bd/cat64x128/ip/cat64x128_blk_mem_gen_0_0/cat64x128_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cat64x128_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Digital_Sys_Design/vga_sprites/vga_sprites.srcs/sources_1/bd/cat64x128/ip/cat64x128_blk_mem_gen_0_0/cat64x128_blk_mem_gen_0_0.xci
# IP: The module: 'cat64x128_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Digital_Sys_Design/vga_sprites/vga_sprites.gen/sources_1/bd/cat64x128/ip/cat64x128_blk_mem_gen_0_0/cat64x128_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cat64x128_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
